### ISSUE TITLE
EpitopePrediction ANN Classes create new Allele objects on predict

### ISSUE THREAD

**Issue by b-schubert** [KohlbacherLab/epytope#38]
The implementations in ANN.py in EpitopePrediction create new ```allele``` objects during prediction. Therefore the ```allele``` objects stored are not the same as the ones used as input and don't have the same information content (e.g., don't have the field ```prob``` set) which causes problems in downstream tasks.

**Comment by christopher-mohr** [comment]
@jonasscheid do you remember if we addressed this in the latest `dev` ?

**Comment by jonasscheid** [comment]
No unfortunately we did not.. This also occurs for the Implementations in `External.py`, however not in `PSSM.py` . I'll have a look at it

**Comment by jonasscheid** [comment]
This bug occurs because `convert_alleles` converts the Allele Obj to a string representation as input for a predictor. Afterwards with `revert_allele_repr` it will be turned into a new Allele Obj based on the string representation. I suppose a dictionary with {Allele Obj: Allele_str_repr, ..} solves that problem.

**Comment by b-schubert** [comment]
Yes indeed and that’s also how it was implemented in external.pay
